spring:
  application:
    name: fabrica

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # Exibe as consultas
    properties:
      hibernate:
        format_sql: true # Formata o SQL para
        hbm2ddl:
          auto: update # auto update
    hibernate:
      ddl-auto: update #bug

management:
  endpoints:
    web:
      exposure:
        # Expõe todos os endpoints disponíveis no Actuator (health, info, metrics, env, beans, mappings, etc.)
        include: "*"
  endpoint:
    health:
      # Mostra os detalhes completos do health check (ex: status do banco de dados, espaço em disco)
      show-details: always
      # Mostra os componentes individuais que formam o status de health
      show-components: always
  info:
    # Habilita a exibição de variáveis de ambiente no endpoint /actuator/info
    env:
      enabled: true
    # Exibe informações do Java e do Sistema Operacional no endpoint /actuator/info
    java:
      enabled: true
    os:
      enabled: true

